version: "3.8"

services:
  scylla:
    image: scylladb/scylla:6.1
    container_name: scylla_mingle
    command: --smp 1 --memory 1G --overprovisioned 1 --api-address 0.0.0.0
    environment:
      - SCYLLA_USER=${SCYLLA_USER:-scylla}
      - SCYLLA_PASSWORD=${SCYLLA_PASSWORD:-scyllapassword}
    ports:
      - "${SCYLLA_PORT:-9042}:9042"
    volumes:
      - scylla_mingle_data:/var/lib/scylla
    networks:
      - scylla_mingle_net
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u",
          "${SCYLLA_USER:-scylla}",
          "-p",
          "${SCYLLA_PASSWORD:-scyllapassword}",
          "-e",
          "describe keyspaces;",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  scylla_mingle_data:

networks:
  scylla_mingle_net:
