services:
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_URL: bolt://database:7687
      DB_USER: neo4j:5.20
      DB_PASS: ${DB_PASS}
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  database:
    image: neo4j
    restart: always
    ports:
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/${DB_PASS}
    healthcheck:
      test: wget http://localhost:7487 || exit 1
      interval: 3s
      timeout: 10s
      retries: 5
