services:
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_SOURCE: "postgresql://postgres:example@postgres:5432/mingle_db?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mingle_db
    healthcheck:
      test: pg_isready -U postgres -d mingle_db
      interval: 3s
      timeout: 3s
      retries: 5
