DROP TABLE IF EXISTS users_subscriptions CASCADE;
DROP TABLE IF EXISTS comment_likes CASCADE;
DROP TABLE IF EXISTS post_likes CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP VIEW IF EXISTS comment_info CASCADE;
DROP VIEW IF EXISTS post_info CASCADE;
