// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id int64) error
	DeleteCommentLike(ctx context.Context, arg DeleteCommentLikeParams) error
	DeletePost(ctx context.Context, id int64) error
	DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListCommentLikes(ctx context.Context, commentID int64) ([]CommentLike, error)
	ListPostComments(ctx context.Context, postID int64) ([]Comment, error)
	ListPostLikes(ctx context.Context, postID int64) ([]PostLike, error)
	ListUserPosts(ctx context.Context, authorID int64) ([]Post, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
