DROP DATABASE IF EXISTS mew_mingle_db;
CREATE DATABASE mew_mingle_db;
USE mew_mingle_db;

CREATE TABLE IF NOT EXISTS users (
	id         INT UNSIGNED    NOT NULL AUTO_INCREMENT,
	email      VARCHAR(255)    NOT NULL,
	first_name VARCHAR(255)    NOT NULL,
	last_name  VARCHAR(255)    NOT NULL,
	PASSWORD   VARCHAR(255)    NOT NULL,
	created_at TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
	UNIQUE KEY (email)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS projects (
	id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name       VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS tasks (
	id             INT UNSIGNED    NOT NULL AUTO_INCREMENT,
	name           VARCHAR(255)    NOT NULL,
	STATUS         ENUM ('TODO', 'IN_PROGRESS', 'IN_TESTING', 'DONE') NOT NULL DEFAULT 'TODO',
	project_id     INT UNSIGNED    NOT NULL,
	assigned_to    INT UNSIGNED    NOT NULL,
	created_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
	FOREIGN KEY (project_id) REFERENCES projects (id),
	FOREIGN KEY (assigned_to) REFERENCES users (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS posts (
	id         INT UNSIGNED    NOT NULL AUTO_INCREMENT,
	content    VARCHAR(255)    NOT NULL,
	author_id  INT UNSIGNED    NOT NULL,
	created_at TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
	FOREIGN KEY (author_id) REFERENCES users (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS COMMENT (
	id             INT UNSIGNED    NOT NULL AUTO_INCREMENT,
	content        VARCHAR(255)    NOT NULL,
	author_id      INT UNSIGNED    NOT NULL,
	post_id        INT UNSIGNED    NOT NULL,
	created_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
	FOREIGN KEY (author_id) REFERENCES users (id),
	FOREIGN KEY (post_id) REFERENCES posts (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
